In [6]:
import polars as pl

In [ ]:
raw = pl.read_csv("../data/raw_data/2026_04_Abril_qualitat_aire_BCN.csv")
raw

shape: (2_370, 57)
┌────────────────┬───────────┬───────────────┬───────────┬───┬─────┬─────┬─────┬─────┐
│ CODI_PROVINCIA ┆ PROVINCIA ┆ CODI_MUNICIPI ┆ MUNICIPI  ┆ … ┆ H23 ┆ V23 ┆ H24 ┆ V24 │
│ ---            ┆ ---       ┆ ---           ┆ ---       ┆   ┆ --- ┆ --- ┆ --- ┆ --- │
│ i64            ┆ str       ┆ i64           ┆ str       ┆   ┆ str ┆ str ┆ str ┆ str │
╞════════════════╪═══════════╪═══════════════╪═══════════╪═══╪═════╪═════╪═════╪═════╡
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 1   ┆ V   ┆ 1   ┆ V   │
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 1   ┆ V   ┆ 1   ┆ V   │
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 1   ┆ V   ┆ 1   ┆ V   │
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 1   ┆ V   ┆ 2   ┆ V   │
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 1   ┆ V   ┆ 1   ┆ V   │
│ …              ┆ …         ┆ …             ┆ …         ┆ … ┆ …   ┆ …   ┆ …   ┆ …   │
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 187 ┆ V   ┆ 202 ┆ V   │
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 349 ┆ V   ┆ 292 ┆ V   │
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 169 ┆ V   ┆ 187 ┆ V   │
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 184 ┆ V   ┆ 174 ┆ V   │
│ 8              ┆ Barcelona ┆ 19            ┆ Barcelona ┆ … ┆ 219 ┆ V   ┆ 227 ┆ V   │
└────────────────┴───────────┴───────────────┴───────────┴───┴─────┴─────┴─────┴─────┘

In [5]:
metadata = pl.read_csv("../data/raw_data/2026_qualitat_aire_estacions.csv")
metadata

shape: (71, 15)
┌─────────┬─────────────┬───────────┬─────┬───┬─────────────┬────────┬─────────┬───────────────────┐
│ Estacio ┆ nom_cabina  ┆ codi_dtes ┆ zqa ┆ … ┆ Nom_barri   ┆ Clas_1 ┆ Clas_2  ┆ Codi_Contaminant  │
│ ---     ┆ ---         ┆ ---       ┆ --- ┆   ┆ ---         ┆ ---    ┆ ---     ┆ ---               │
│ i64     ┆ str         ┆ str       ┆ i64 ┆   ┆ str         ┆ str    ┆ str     ┆ i64               │
╞═════════╪═════════════╪═══════════╪═════╪═══╪═════════════╪════════╪═════════╪═══════════════════╡
│ 4       ┆ Barcelona - ┆ I2        ┆ 1   ┆ … ┆ el Poblenou ┆ Urbana ┆ Fons    ┆ 8                 │
│         ┆ Poblenou    ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
│ 4       ┆ Barcelona - ┆ I2        ┆ 1   ┆ … ┆ el Poblenou ┆ Urbana ┆ Fons    ┆ 10                │
│         ┆ Poblenou    ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
│ 4       ┆ Barcelona - ┆ I2        ┆ 1   ┆ … ┆ el Poblenou ┆ Urbana ┆ Fons    ┆ 7                 │
│         ┆ Poblenou    ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
│ 4       ┆ Barcelona - ┆ I2        ┆ 1   ┆ … ┆ el Poblenou ┆ Urbana ┆ Fons    ┆ 12                │
│         ┆ Poblenou    ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
│ 42      ┆ Barcelona - ┆ ID        ┆ 1   ┆ … ┆ Sants       ┆ Urbana ┆ Fons    ┆ 8                 │
│         ┆ Sants       ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
│ …       ┆ …           ┆ …         ┆ …   ┆ … ┆ …           ┆ …      ┆ …       ┆ …                 │
│ 81      ┆ Barcelona - ┆ NA        ┆ 1   ┆ … ┆ Navas       ┆ Urbana ┆ Trànsit ┆ 7                 │
│         ┆ Navas       ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
│ 81      ┆ Barcelona - ┆ NA        ┆ 1   ┆ … ┆ Navas       ┆ Urbana ┆ Trànsit ┆ 10                │
│         ┆ Navas       ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
│ 81      ┆ Barcelona - ┆ NA        ┆ 1   ┆ … ┆ Navas       ┆ Urbana ┆ Trànsit ┆ 12                │
│         ┆ Navas       ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
│ 81      ┆ Barcelona - ┆ NA        ┆ 1   ┆ … ┆ Navas       ┆ Urbana ┆ Trànsit ┆ 14                │
│         ┆ Navas       ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
│ 81      ┆ Barcelona - ┆ NA        ┆ 1   ┆ … ┆ Navas       ┆ Urbana ┆ Trànsit ┆ 9                 │
│         ┆ Navas       ┆           ┆     ┆   ┆             ┆        ┆         ┆                   │
└─────────┴─────────────┴───────────┴─────┴───┴─────────────┴────────┴─────────┴───────────────────┘

In [ ]:
j = raw.join(
    metadata,
    on="codi_dtes"
    how="inner"
)

In [7]:
accidents = pl.read_csv("../data/raw_data/2025_accidents_gu_bcn.csv")

In [8]:
accidents

shape: (7_741, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Numero_ex ┆ Codi_dist ┆ Nom_distr ┆ Codi_barr ┆ … ┆ Coordenad ┆ Coordenad ┆ Longitud_ ┆ Latitud_ │
│ pedient   ┆ ricte     ┆ icte      ┆ i         ┆   ┆ a_UTM_Y_E ┆ a_UTM_X_E ┆ WGS84     ┆ WGS84    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ D50       ┆ D50       ┆ ---       ┆ ---      │
│ str       ┆ i64       ┆ str       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025S0000 ┆ 3         ┆ Sants-Mon ┆ 11        ┆ … ┆ 429920.02 ┆ 4.5795e6  ┆ 2.1609994 ┆ 41.36198 │
│ 01        ┆           ┆ tjuïc     ┆           ┆   ┆ 5         ┆           ┆           ┆ 1        │
│ 2025S0000 ┆ 10        ┆ Sant      ┆ 65        ┆ … ┆ 432504.37 ┆ 4.5850e6  ┆ 2.191279  ┆ 41.41197 │
│ 02        ┆           ┆ Martí     ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ 2025S0000 ┆ 10        ┆ Sant      ┆ 66        ┆ … ┆ 432383.51 ┆ 4.5834e6  ┆ 2.190016  ┆ 41.39721 │
│ 03        ┆           ┆ Martí     ┆           ┆   ┆ 8         ┆           ┆           ┆ 8        │
│ 2025S0000 ┆ 5         ┆ Sarrià-Sa ┆ 26        ┆ … ┆ 429100.95 ┆ 4.5832e6  ┆ 2.150778  ┆ 41.39499 │
│ 04        ┆           ┆ nt        ┆           ┆   ┆ 7         ┆           ┆           ┆ 3        │
│           ┆           ┆ Gervasi   ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025S0000 ┆ 4         ┆ Les Corts ┆ 19        ┆ … ┆ 427208.07 ┆ 4.5817e6  ┆ 2.128311  ┆ 41.38181 │
│ 05        ┆           ┆           ┆           ┆   ┆ 3         ┆           ┆           ┆ 3        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2025S0077 ┆ 9         ┆ Sant      ┆ 61        ┆ … ┆ 432572.73 ┆ 4.5862e6  ┆ 2.191959  ┆ 41.42306 │
│ 38        ┆           ┆ Andreu    ┆           ┆   ┆ 6         ┆           ┆           ┆ 8        │
│ 2025S0077 ┆ 3         ┆ Sants-Mon ┆ 18        ┆ … ┆ 428182.06 ┆ 4.5818e6  ┆ 2.139954  ┆ 41.38226 │
│ 39        ┆           ┆ tjuïc     ┆           ┆   ┆ 9         ┆           ┆           ┆ 3        │
│ 2025S0077 ┆ 3         ┆ Sants-Mon ┆ 11        ┆ … ┆ 430989.76 ┆ 4.5808e6  ┆ 2.173637  ┆ 41.37400 │
│ 40        ┆           ┆ tjuïc     ┆           ┆   ┆ 9         ┆           ┆           ┆ 4        │
│ 2025S0077 ┆ 2         ┆ Eixample  ┆ 9         ┆ … ┆ 429183.91 ┆ 4.5818e6  ┆ 2.1519314 ┆ 41.38256 │
│ 41        ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆ 9        │
│ 2025S0077 ┆ 1         ┆ Ciutat    ┆ 1         ┆ … ┆ 430310.93 ┆ 4.5812e6  ┆ 2.16548   ┆ 41.37710 │
│ 42        ┆           ┆ Vella     ┆           ┆   ┆ 3         ┆           ┆           ┆ 9        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
obres = pl.read_json("../data/raw_data/obres_espai_public.csv")